name: a workflow for build the website
on: 
 workflow-dispatch:
jobs:
  build-jobs:
    name: super
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: checkout code
    - name: chekout code
      run: echo heloworld
    - name: index.html
      run: cat Index.html

